# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jicama/p3/Games/DTR-vita

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jicama/p3/Games/DTR-vita

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jicama/p3/Games/DTR-vita/CMakeFiles /home/jicama/p3/Games/DTR-vita//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jicama/p3/Games/DTR-vita/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BC2.elf

# Build rule for target.
BC2.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BC2.elf
.PHONY : BC2.elf

# fast build rule for target.
BC2.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/build
.PHONY : BC2.elf/fast

#=============================================================================
# Target rules for targets named BC2.elf-velf

# Build rule for target.
BC2.elf-velf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BC2.elf-velf
.PHONY : BC2.elf-velf

# fast build rule for target.
BC2.elf-velf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf-velf.dir/build.make CMakeFiles/BC2.elf-velf.dir/build
.PHONY : BC2.elf-velf/fast

#=============================================================================
# Target rules for targets named eboot.bin-self

# Build rule for target.
eboot.bin-self: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eboot.bin-self
.PHONY : eboot.bin-self

# fast build rule for target.
eboot.bin-self/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eboot.bin-self.dir/build.make CMakeFiles/eboot.bin-self.dir/build
.PHONY : eboot.bin-self/fast

#=============================================================================
# Target rules for targets named DuckTales.vpk-vpk

# Build rule for target.
DuckTales.vpk-vpk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DuckTales.vpk-vpk
.PHONY : DuckTales.vpk-vpk

# fast build rule for target.
DuckTales.vpk-vpk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DuckTales.vpk-vpk.dir/build.make CMakeFiles/DuckTales.vpk-vpk.dir/build
.PHONY : DuckTales.vpk-vpk/fast

#=============================================================================
# Target rules for targets named copy

# Build rule for target.
copy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 copy
.PHONY : copy

# fast build rule for target.
copy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copy.dir/build.make CMakeFiles/copy.dir/build
.PHONY : copy/fast

loader/dialog.obj: loader/dialog.c.obj
.PHONY : loader/dialog.obj

# target to build an object file
loader/dialog.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/dialog.c.obj
.PHONY : loader/dialog.c.obj

loader/dialog.i: loader/dialog.c.i
.PHONY : loader/dialog.i

# target to preprocess a source file
loader/dialog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/dialog.c.i
.PHONY : loader/dialog.c.i

loader/dialog.s: loader/dialog.c.s
.PHONY : loader/dialog.s

# target to generate assembly for a file
loader/dialog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/dialog.c.s
.PHONY : loader/dialog.c.s

loader/etc1_utils.obj: loader/etc1_utils.c.obj
.PHONY : loader/etc1_utils.obj

# target to build an object file
loader/etc1_utils.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/etc1_utils.c.obj
.PHONY : loader/etc1_utils.c.obj

loader/etc1_utils.i: loader/etc1_utils.c.i
.PHONY : loader/etc1_utils.i

# target to preprocess a source file
loader/etc1_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/etc1_utils.c.i
.PHONY : loader/etc1_utils.c.i

loader/etc1_utils.s: loader/etc1_utils.c.s
.PHONY : loader/etc1_utils.s

# target to generate assembly for a file
loader/etc1_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/etc1_utils.c.s
.PHONY : loader/etc1_utils.c.s

loader/jni_patch.obj: loader/jni_patch.c.obj
.PHONY : loader/jni_patch.obj

# target to build an object file
loader/jni_patch.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/jni_patch.c.obj
.PHONY : loader/jni_patch.c.obj

loader/jni_patch.i: loader/jni_patch.c.i
.PHONY : loader/jni_patch.i

# target to preprocess a source file
loader/jni_patch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/jni_patch.c.i
.PHONY : loader/jni_patch.c.i

loader/jni_patch.s: loader/jni_patch.c.s
.PHONY : loader/jni_patch.s

# target to generate assembly for a file
loader/jni_patch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/jni_patch.c.s
.PHONY : loader/jni_patch.c.s

loader/main.obj: loader/main.c.obj
.PHONY : loader/main.obj

# target to build an object file
loader/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/main.c.obj
.PHONY : loader/main.c.obj

loader/main.i: loader/main.c.i
.PHONY : loader/main.i

# target to preprocess a source file
loader/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/main.c.i
.PHONY : loader/main.c.i

loader/main.s: loader/main.c.s
.PHONY : loader/main.s

# target to generate assembly for a file
loader/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/main.c.s
.PHONY : loader/main.c.s

loader/pthr.obj: loader/pthr.c.obj
.PHONY : loader/pthr.obj

# target to build an object file
loader/pthr.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/pthr.c.obj
.PHONY : loader/pthr.c.obj

loader/pthr.i: loader/pthr.c.i
.PHONY : loader/pthr.i

# target to preprocess a source file
loader/pthr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/pthr.c.i
.PHONY : loader/pthr.c.i

loader/pthr.s: loader/pthr.c.s
.PHONY : loader/pthr.s

# target to generate assembly for a file
loader/pthr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/pthr.c.s
.PHONY : loader/pthr.c.s

loader/so_util.obj: loader/so_util.c.obj
.PHONY : loader/so_util.obj

# target to build an object file
loader/so_util.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/so_util.c.obj
.PHONY : loader/so_util.c.obj

loader/so_util.i: loader/so_util.c.i
.PHONY : loader/so_util.i

# target to preprocess a source file
loader/so_util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/so_util.c.i
.PHONY : loader/so_util.c.i

loader/so_util.s: loader/so_util.c.s
.PHONY : loader/so_util.s

# target to generate assembly for a file
loader/so_util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BC2.elf.dir/build.make CMakeFiles/BC2.elf.dir/loader/so_util.c.s
.PHONY : loader/so_util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BC2.elf-velf"
	@echo "... DuckTales.vpk-vpk"
	@echo "... copy"
	@echo "... eboot.bin-self"
	@echo "... BC2.elf"
	@echo "... loader/dialog.obj"
	@echo "... loader/dialog.i"
	@echo "... loader/dialog.s"
	@echo "... loader/etc1_utils.obj"
	@echo "... loader/etc1_utils.i"
	@echo "... loader/etc1_utils.s"
	@echo "... loader/jni_patch.obj"
	@echo "... loader/jni_patch.i"
	@echo "... loader/jni_patch.s"
	@echo "... loader/main.obj"
	@echo "... loader/main.i"
	@echo "... loader/main.s"
	@echo "... loader/pthr.obj"
	@echo "... loader/pthr.i"
	@echo "... loader/pthr.s"
	@echo "... loader/so_util.obj"
	@echo "... loader/so_util.i"
	@echo "... loader/so_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

